### ISSUE TITLE
How can I get the "checksum.json" file?

### ISSUE THREAD

**Issue by pokewiz** [paimoe/eu4map#4]
Sorry for my bad English and Python skills.
I want to use your tools to generate the provdata.json file of the current version. But it shows ”FileNotFoundError: [Errno 2] No such file or directory: 'checksum.json'“.
How to make it works? And how to generate this file? Thank you!

**Comment by paimoe** [comment]
(Been a while since I've used this)

the checksum file should be generated automatically, although I don't think it's necessary anyway, so you can probably comment out [these two lines](https://github.com/paimoe/eu4map/blob/master/parsers/base.py#L61)

Also, I can't guarantee it works on the latest version of course

**Comment by pokewiz** [comment]
Thanks for your replying. I try to comment out those lines, but It's still doesn't work.

$ python eu4map.py country
Traceback (most recent call last):
  File "eu4map.py", line 118, in <module>
    p = eval("{0}Parser()".format(opts.action.capitalize()))
  File "<string>", line 1, in <module>
  File "C:\Users\username\Documents\eu4map\parsers\countries.py", line 14, in __init__
    super().__init__(test=test)
  File "C:\Users\username\Documents\eu4map\parsers\base.py", line 294, in __init__
    self.load_language('english')
  File "C:\Users\username\Documents\eu4map\parsers\base.py", line 329, in load_language
    citems = gen_splitter.findall(cdata['l_english'])
KeyError: 'l_english'

Is it my path setting or python‘s module installation problem? Thanks again!

**Comment by paimoe** [comment]
Looks like it would be an issue with this line:

`data = load_yaml('achievements_l_english.yml')`

Does your Eu4 install have the english language files? (I assume it does). And I'm assuming you changed the EU4_PATH variable in parsers/base.py
